### ISSUE TITLE
Telepítés - hogyan?

### ISSUE THREAD

**Issue by sanchomuzax** [csorbazoli/CodieController#1]
Szia! Hogyan telepíthető az offline verzió mellé a plugin/kiterjesztés?

Ki szeretném próbálni. Van egy Codie-m, és szeretnék vele valamit kezdeni.

Segítséged előre is köszönöm! :)

**Comment by csorbazoli** [comment]
Szia, sajnos nem vittem végig a fejlesztést, így nem tudod kipróbálni:(
Addig jutottam, hogy megírtam Java-ban a web servert, ami a scrath-ben
definiált blokkokat implementálja.
Viszont kellett volna még írnom hozzá egy C++ illesztőt, mivel Java-ban a
windows-hoz nem találtam akkor megfelelő Bluetooth 4-es LTE drivert. Talán
azóta már van ilyen (akkor csak androidos library volt).

Ha mégis jutsz vele valamire, akkor kérlek, értesíts. Mert a Codie-t azóta
félreraktuk, lévén nem volt hozzá programozói felület.

**Comment by sanchomuzax** [comment]
Köszi, és sajnálom, hogy félbe maradt! :)

Ha bármi van, jelzem.

Mellékelem a közben megszűnt Codie API SDK elérhetőségeket, valamint a Windows példaprogramot, gondolom ez megvan Neked is: 
https://1drv.ms/u/s!Avi1CwnN5T1xnr0IVG-K_rMYpJi2Hw

**Comment by csorbazoli** [comment]
Szia, a dokumentáció megvolt már a példaprogramokkal, de a CodieGateway nem. Ami pont az, amire szükségem lenne a befejezéshez, de mivel ehhez nincs semmi dokumentáció, ezért nem tudom, milyen http requestekkel lehetne megszólítani. A scratch-hez írt kiegészítőjük sem elérhető már. Ez lenne a könnyebb falat, magam is ez utóbbit írtam meg.

**Comment by sanchomuzax** [comment]
A legkisebb fiam unszolására ráengedtem a Codie-ra a Claude Code-t, és sikerült mozgásra bírni, csipogtatni és a fényekkel játszani. A tegnap éjszakai vibe coding eredménye:
https://github.com/sanchomuzax/codie

**Comment by csorbazoli** [comment]
Gratulálok, megnéztem a GitHub projekteket, nagyon jól néz ki. Az mindig egy jó jel, ha vannak tesztek és könnyen ki lehet kipróbálni.
Nekem már nincs meg a Codie-m 😞

**Comment by sanchomuzax** [comment]
Érdekes sorsa lett volna a Codie-nak anno, ha rendelkezésetekre állt volna a Claude Code. 🤗 Akkor vélhetően minden másképp alakul.
